import { getAIReport } from "@/lib/data";
import { FileText, Sparkles } from "lucide-react";
import Link from "next/link";

export const dynamic = "force-dynamic";

export default function ReportPage() {
  const aiReport = getAIReport();

  if (!aiReport) {
    return (
      <div className="flex flex-col items-center justify-center h-full gap-4">
        <FileText className="w-12 h-12 text-muted" />
        <div className="text-center">
          <h2 className="text-lg font-bold mb-1">No AI Report Yet</h2>
          <p className="text-muted text-sm mb-4">
            Run audits first, then generate an AI report from the Audits page.
          </p>
          <Link
            href="/audits"
            className="inline-flex items-center gap-2 px-4 py-2 rounded-xl text-sm font-semibold bg-accent text-white hover:bg-accent/90 transition"
          >
            <Sparkles className="w-4 h-4" />
            Go to Audits
          </Link>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6 max-w-4xl">
      <div>
        <h1 className="text-2xl font-bold tracking-tight">AI Audit Report</h1>
        <p className="text-sm text-muted mt-1">
          Generated by Kimi K2.5 via Featherless AI
        </p>
      </div>

      <div className="bg-card border border-card-border rounded-2xl p-8">
        <article className="prose prose-invert prose-sm max-w-none
          [&_h1]:text-xl [&_h1]:font-bold [&_h1]:text-foreground [&_h1]:mt-8 [&_h1]:mb-4
          [&_h2]:text-lg [&_h2]:font-bold [&_h2]:text-foreground [&_h2]:mt-8 [&_h2]:mb-3
          [&_h3]:text-base [&_h3]:font-semibold [&_h3]:text-foreground [&_h3]:mt-6 [&_h3]:mb-2
          [&_h4]:text-sm [&_h4]:font-semibold [&_h4]:text-foreground/90 [&_h4]:mt-4 [&_h4]:mb-2
          [&_p]:text-foreground/75 [&_p]:leading-relaxed [&_p]:my-3
          [&_ul]:text-foreground/75 [&_ul]:my-2
          [&_ol]:text-foreground/75 [&_ol]:my-2
          [&_li]:my-1 [&_li]:leading-relaxed
          [&_strong]:text-foreground [&_strong]:font-semibold
          [&_em]:text-foreground/60
          [&_hr]:border-card-border [&_hr]:my-6
          [&_table]:w-full [&_table]:my-4
          [&_th]:text-left [&_th]:text-xs [&_th]:font-semibold [&_th]:text-muted [&_th]:uppercase [&_th]:tracking-wider [&_th]:p-3 [&_th]:border-b [&_th]:border-card-border
          [&_td]:p-3 [&_td]:text-sm [&_td]:text-foreground/75 [&_td]:border-b [&_td]:border-card-border/50
          [&_code]:bg-background [&_code]:px-1.5 [&_code]:py-0.5 [&_code]:rounded [&_code]:text-xs [&_code]:font-mono [&_code]:text-accent/80
        ">
          <MarkdownRenderer content={aiReport} />
        </article>
      </div>
    </div>
  );
}

function MarkdownRenderer({ content }: { content: string }) {
  const html = content
    .replace(/^#### (.+)$/gm, "<h4>$1</h4>")
    .replace(/^### (.+)$/gm, "<h3>$1</h3>")
    .replace(/^## (.+)$/gm, "<h2>$1</h2>")
    .replace(/^# (.+)$/gm, "<h1>$1</h1>")
    .replace(/^---$/gm, "<hr />")
    .replace(/\*\*\*(.+?)\*\*\*/g, "<strong><em>$1</em></strong>")
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/\*(.+?)\*/g, "<em>$1</em>")
    .replace(/^\|(.+)\|$/gm, (match) => {
      const cells = match.split("|").filter(Boolean).map((c) => c.trim());
      if (cells.every((c) => /^[-:]+$/.test(c))) return "<!-- sep -->";
      return `<tr>${cells.map((c) => `<td>${c}</td>`).join("")}</tr>`;
    })
    .replace(/^[\*\-] (.+)$/gm, "<li>$1</li>")
    .replace(/^\d+\.\s+(.+)$/gm, "<li>$1</li>")
    .replace(/^(?!<[a-z]|<!--)(.+)$/gm, (match) => match.trim() ? `<p>${match}</p>` : "")
    .replace(/(<li>.*<\/li>\n?)+/g, (match) => `<ul>${match}</ul>`)
    .replace(/(<tr>.*<\/tr>\n?)+/g, (match) => `<table>${match}</table>`)
    .replace(/<!--.*?-->/g, "");

  return <div dangerouslySetInnerHTML={{ __html: html }} />;
}
